### ISSUE TITLE
Weekly/63 for 2016/12/28

### ISSUE THREAD

**Issue by ComMouse** [dyweb/weekly#11]
2016/12/28, 总第六十三期 -> @dyweb/mos

投稿:

Web
- [x] @at15
- [ ] @swaylq
- [x] @ComMouse
- [ ] @JasonQSY
- [ ] @LukeXuan
- [ ] @kdplus
- [ ] @Bluemit
- [ ] @bjmiao

MOS
- [ ] @gaocegege
- [ ] @mrmiywj 
- [ ] @arrowrowe
- [ ] @codeworm96 
- [ ] @JasonQSY 

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by at15** [comment]
https://allenkim67.github.io/bittorrent/2016/05/04/how-to-make-your-own-bittorrent-client.html

**Comment by at15** [comment]
https://github.com/wepayui/wepayui cc @ComMouse

**Comment by at15** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Rust install rust server on linux cc @gaocegege

**Comment by at15** [comment]
https://github.com/fatedier/frp A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet

**Comment by LukeXuan** [comment]
wow such a rust

**Comment by ComMouse** [comment]
```yaml
    name: 浏览器的工作原理：新式网络浏览器幕后揭秘
    link: https://www.html5rocks.com/zh/tutorials/internals/howbrowserswork/
    description: 
    quote: 网络浏览器很可能是使用最广的软件。在这篇入门文章中，我将会介绍它们的幕后工作原理。我们会了解到，从您在地址栏输入 google.com 直到您在浏览器屏幕上看到 Google 首页的整个过程中都发生了些什么。
    cc: @bjmiao @Pengzhenghao @web-novice
    ```
@bjmiao @Pengzhenghao @dyweb/web-novice
