### ISSUE TITLE
Weekly/64 for 2017/1/11

### ISSUE THREAD

**Issue by ComMouse** [dyweb/weekly#12]
2017/1/11, 总第六十四期 -> @dyweb/mos

投稿:

Web
- [x] @at15
- [ ] @swaylq
- [x] @ComMouse
- [ ] @JasonQSY
- [ ] @LukeXuan
- [ ] @mingzz
- [ ] @kdplus
- [ ] @Bluemit 
- [ ] @bjmiao
- [ ] @dbshch
- [ ] @GigaFlower
- [ ] @jasonliu747
- [ ] @lmh16
- [ ] @ningxiaohan
- [ ] @PengZhenghao
- [ ] @XinJack

MOS
- [x] @gaocegege
- [ ] @mrmiywj 
- [ ] @arrowrowe
- [x] @codeworm96 
- [ ] @JasonQSY 

Other
- [ ] @dyweb/android-dev 
- [ ] @dyweb/ios-dev 

__Please TICK YOUR NAME after you have posted a share!! Feel free to add your name if you are not listed above.__

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by ComMouse** [comment]
@dyweb/web-novice @dyweb/mos

**Comment by at15** [comment]
https://github.com/Knetic/govaluate Arbitrary expression evaluation for golang

**Comment by at15** [comment]
http://iknowwhatyoudownload.com/ torrent download history by IP

**Comment by at15** [comment]
https://krita.org/ a PS alternative on *nix, and also works on windows cc @daniyuu 

compared with GIMP, oh my

**Comment by arrowrowe** [comment]
@at15 Krita 一直在用, 每次关闭都报错 :(

**Comment by codeworm96** [comment]
```yaml
name: Tokei (時計)
link: https://github.com/Aaronepower/tokei
description: >
     Tokei is a program that displays statistics about your code.
     Tokei will show number of files, total lines within those files and code, comments,
     and blanks grouped by language.

     (Provides badges!)
quote: 
cc: 
```

**Comment by at15** [comment]
@codeworm96 现在 weekly generator 支持 tag 的 syntax 么? i.e.

````yaml
tag:
  - rust
  - productivity
````

**Comment by gaocegege** [comment]
```
name: Monodraw
link: https://monodraw.helftone.com/
description: >
     Powerful ASCII art editor designed for the Mac.
quote: 
cc: 
```

**Comment by at15** [comment]
@gaocegege forgot `yaml`

**Comment by codeworm96** [comment]
@at15 Currently, tag/keyword fields are ignored... Because how to render them are not defined.

**Comment by at15** [comment]
https://github.com/yahoo/gryffin Gryffin is a large scale web security scanning platform  cc @ComMouse  have a try on tongqu 0.o?

**Comment by ComMouse** [comment]
```yaml
name: xLua
link: https://github.com/Tencent/xLua
description:  > 
    xLua is a hot-fix solution plugin for Unity3D, it supports android, ios, windows, osx, etc.
quote: 
cc: 
```
