### ISSUE TITLE
Weekly/65 for 2017/1/25

### ISSUE THREAD

**Issue by ComMouse** [dyweb/weekly#13]
2017/1/25, 总第六十五期 -> @dyweb/mos

投稿:

Web
- [x] @at15
- [ ] @swaylq
- [ ] @ComMouse
- [ ] @JasonQSY
- [x] @LukeXuan
- [ ] @mingzz
- [ ] @kdplus
- [ ] @Bluemit 
- [ ] @bjmiao
- [ ] @dbshch
- [ ] @GigaFlower
- [ ] @jasonliu747
- [ ] @lmh16
- [ ] @ningxiaohan
- [ ] @PengZhenghao
- [ ] @XinJack

MOS
- [ ] @gaocegege
- [ ] @mrmiywj 
- [ ] @arrowrowe
- [ ] @codeworm96 
- [ ] @JasonQSY 

Other
- [ ] @dyweb/android-dev 
- [ ] @dyweb/ios-dev 

__Please TICK YOUR NAME after you have posted a share!! Feel free to add your name if you are not listed above.__

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by LukeXuan** [comment]
```yaml
name: lebab
link: https://github.com/lebab/lebab
description: Hey it's 2017 now. Why are you guys using ES5?
```

**Comment by LukeXuan** [comment]
```yaml
name: Airflow
link: https://airflow.incubator.apache.org/index.html
description: System for automated workflows featuring DAG.
```

**Comment by at15** [comment]
````yaml
name: ga-beacon
link: https://github.com/igrigorik/ga-beacon
description: use google analysis for your github readme
````

**Comment by at15** [comment]
````yaml
name: tolerant-php-parser
link: https://github.com/Microsoft/tolerant-php-parser
description: Microsoft love PHP (I made it up)
cc: @ComMouse
````

@ComMouse

**Comment by at15** [comment]
````yaml
name: The Cathedral and the Bazaar
link: http://www.catb.org/esr/writings/homesteading/cathedral-bazaar
description: Why Linux development style success and what should we learn from it when we deal with software engineering
cc: @ComMouse @gaocegege @arrowrowe
````

@ComMouse @gaocegege @arrowrowe

**Comment by at15** [comment]
````yaml
name: syntax_sugar_python
link: https://github.com/czheo/syntax_sugar_python
description: 学校小伙伴写的 pipe style py
cc: @arrowrowe @gaocegege
````
cc @gaocegege @arrowrowe

**Comment by at15** [comment]
`````yaml
name: anime database
link: https://github.com/anilogia/animedb
description: 看不懂日语
cc: @arrowrowe
`````
cc @arrowrowe
