### ISSUE TITLE
Weekly/66 for 2017/2/8

### ISSUE THREAD

**Issue by ComMouse** [dyweb/weekly#14]
2017/2/8, 总第六十六期 -> @dyweb/mos

投稿:

Web
- [x] @at15
- [ ] @swaylq
- [x] @ComMouse
- [ ] @JasonQSY
- [ ] @LukeXuan
- [ ] @mingzz
- [ ] @kdplus
- [ ] @Bluemit 
- [ ] @bjmiao
- [ ] @dbshch
- [ ] @GigaFlower
- [ ] @jasonliu747
- [ ] @lmh16
- [ ] @ningxiaohan
- [ ] @PengZhenghao
- [ ] @XinJack 
- [x] @tq5124 

MOS
- [ ] @gaocegege
- [ ] @mrmiywj 
- [ ] @arrowrowe
- [x] @codeworm96 
- [ ] @JasonQSY 

Other
- [ ] @dyweb/android-dev 
- [ ] @dyweb/ios-dev 

__Please TICK YOUR NAME after you have posted a share!! Feel free to add your name if you are not listed above.__

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by codeworm96** [comment]
```yaml
name: pixi.js
link: https://github.com/pixijs/pixi.js
description: 2D rendering engine that uses webGL with canvas fallback
```

**Comment by ComMouse** [comment]
```yaml
name: CSS Still Sucks 2015
link: http://huangxuan.me/css-sucks-2015
description: An overview of CSS history and future
```

**Comment by at15** [comment]
````yaml
name: Log Structured Merge Tree and Cassandra
link: http://www.slideshare.net/ssuser7e134a/log-structured-merge-tree
description: Course presentation by @at15
````

**Comment by at15** [comment]
````yaml
name: Google Web Designer
link: https://www.google.com/webdesigner/
description: you can use code as well
cc: @scottsun94
````
@scottsun94

**Comment by at15** [comment]
https://www.bigmarker.com/gopheracademy/Distributed-Computing-in-Go-Building-Consensus-with-Raft-Protocol cc @gaocegege

**Comment by ComMouse** [comment]
```yaml
name: GitLab.com Database Incident
link: https://about.gitlab.com/2017/02/01/gitlab-dot-com-database-incident/
description: An summary of a serious ops incident
quote: Yesterday we had a serious incident with one of our databases. We lost six hours of database data (issues, merge requests, users, comments, snippets, etc.) for GitLab.com.
cc: @gaocegege @at15
```

**Comment by tq5124** [comment]
```yams
name: A survey of B-Tree Locking Techniques
link: http://15721.courses.cs.cmu.edu/spring2017/papers/06-latching/a16-graefe.pdf
summary: When implementing B-Tree locking, there are two concepts, locking and latching. Latching protects in-memory data structures between concurrency threads, and should be held only for very short periods. Locking protects database contents (or data in logical) among transactions, and keep in lock manager`s hash table.
```

**Comment by at15** [comment]
````yaml
name: SIGMOD N-grams student contest
link: http://sigmod17contest.athenarc.gr/task.shtml
description: 不限制国家不限制学校组队 .w.
````

cc @mrmiywj @gaocegege @arrowrowe @ComMouse

**Comment by at15** [comment]
````yaml
name: bodymovin
link: https://github.com/bodymovin/bodymovin
description: after effect animation to html
````
@ComMouse

**Comment by at15** [comment]
````yaml
name: TNTSearch
link: https://github.com/teamtnt/tntsearch
description: A fully featured full text search engine written in PHP
````

cc @ComMouse maybe use it on the hr system?

**Comment by codeworm96** [comment]
```yaml
name: Lottie
link: http://airbnb.design/lottie/
description: >
    A mobile library for Android and iOS that parses Adobe After Effects animations exported as json
    with Bodymovin and renders them natively on mobile.
cc: ComMouse, at15
```
cc @ComMouse @at15
