### ISSUE TITLE
Weekly/67 for 2017/2/22

### ISSUE THREAD

**Issue by ComMouse** [dyweb/weekly#15]
2017/2/22, 总第六十七期 -> @dyweb/mos

投稿:

Web
- [x] @at15
- [ ] @swaylq
- [x] @ComMouse
- [ ] @JasonQSY
- [x] @LukeXuan
- [ ] @mingzz
- [ ] @kdplus
- [ ] @Bluemit 
- [ ] @bjmiao
- [ ] @dbshch
- [x] @GigaFlower
- [ ] @jasonliu747
- [ ] @lmh16
- [ ] @ningxiaohan
- [ ] @PengZhenghao
- [ ] @XinJack
- [x] @tq5124 

MOS
- [x] @gaocegege
- [ ] @mrmiywj 
- [ ] @arrowrowe
- [ ] @codeworm96 
- [ ] @JasonQSY 

Other
- [ ] @dyweb/android-dev 
- [ ] @dyweb/ios-dev 

__Please TICK YOUR NAME after you have posted a share!! Feel free to add your name if you are not listed above.__

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by ComMouse** [comment]
```yaml
name: Our Big Frontend Plan Revealed
link: https://about.gitlab.com/2017/02/06/vue-big-plan/
description: Our long term plan to make GitLab as fast and performant as possible with Vue and webpack.
cc: @at15 @arrowrowe
```

**Comment by gaocegege** [comment]
name: Træfɪk
link: https://traefik.io/
description: Træfɪk, a modern reverse proxy.
cc: @gaocegege @at15

**Comment by tq5124** [comment]
```yml
name: Skip List Done Right
link: http://15721.courses.cs.cmu.edu/spring2017/papers/07-oltpindexes1/skiplists-done-right2016.pdf
description: Skip list is an important and widely used data structure but I did not hear about it when I learned data structure in undergraduate school. It can do insert / delete / search in O(logN) on average.
```

**Comment by at15** [comment]
@tq5124 tw 上刚看到 Andrew 分享的yt视频 /w\

**Comment by at15** [comment]
````yaml
name: phpunit-vw
link: https://github.com/hmlb/phpunit-vw
description: It automatically detects CI environments and makes your test suites succeed even with failing assertions or unwanted exceptions \o/
`````

cc @ComMouse @gaocegege 

btw: for js users, pls see https://github.com/auchenberg/volkswagen

**Comment by at15** [comment]
````yaml
name: go-tour
link: https://github.com/uber/go-torch
description: Stochastic flame graph profiler for Go programs
````

cc @gaocegege

**Comment by at15** [comment]
````yaml
name: gopherize
link: https://gopherize.me
````
cc @gaocegege 

![image](https://cloud.githubusercontent.com/assets/5621298/22867528/d016d21a-f13e-11e6-9357-ca69cee92503.png)

**Comment by LukeXuan** [comment]
```yaml
name: Kotlin框架巡礼
url: https://www.qingjingjie.com/blogs/42
```

seems friendly.

**Comment by at15** [comment]
````yaml
name: meshbird 
link: https://github.com/meshbird/meshbird
description: Distributed private networking
`````

cc @gaocegege

**Comment by at15** [comment]
````yaml
name: open source guide
link: https://github.com/github/open-source-guide
````

cc @dyweb/mos

**Comment by at15** [comment]
````yaml
name: ciao
link: https://github.com/01org/ciao
description: Ciao - Cloud Integrated Advanced Orchestrator from Intel open source
````

cc @gaocegege

**Comment by at15** [comment]
````yaml
name: concurrency is not parallelism
link: https://blog.golang.org/concurrency-is-not-parallelism
````

**Comment by at15** [comment]
````yaml
name: TUNA from tsinghua
link: https://tuna.moe/
````

cc @ComMouse @arrowrowe

**Comment by GigaFlower** [comment]
````yaml
name: Metacadamy
link: https://metacademy.org/
description: Searching for hierarchy of knowledge and roadmaps for learning, specialized in Machining Learning
````
