### ISSUE TITLE
Weekly/68 for 2017/3/8

### ISSUE THREAD

**Issue by ComMouse** [dyweb/weekly#16]
2017/3/8, 总第六十八期 -> @dyweb/mos

投稿:

Web
- [x] @at15
- [ ] @swaylq
- [ ] @ComMouse
- [ ] @JasonQSY
- [ ] @LukeXuan
- [ ] @mingzz
- [ ] @kdplus
- [ ] @Bluemit 
- [ ] @bjmiao
- [ ] @dbshch
- [ ] @GigaFlower
- [ ] @jasonliu747
- [ ] @lmh16
- [ ] @ningxiaohan
- [ ] @PengZhenghao
- [ ] @XinJack
- [ ] @tq5124 

MOS
- [ ] @gaocegege
- [ ] @mrmiywj 
- [ ] @arrowrowe
- [ ] @codeworm96 
- [ ] @JasonQSY 

Other
- [ ] @dyweb/android-dev 
- [ ] @dyweb/ios-dev 

__投稿后请在上述名单中 *打钩* ，如果没有列出各位的账号，也欢迎补充上来~__

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by at15** [comment]
````yaml
name: Design pattern for humans
link: https://github.com/kamranahmedse/design-patterns-for-humans
````

**Comment by at15** [comment]
````yaml
name: A Web GUI for GDB
link: https://github.com/cs01/gdbgui
````

**Comment by at15** [comment]
````yaml
name: Containerized Data Analytics
link: https://github.com/pachyderm/pachyderm
description: Git for Data Science: Pachyderm offers complete version control for even the largest data sets
````

cc @gaocegege

**Comment by at15** [comment]
````yaml
name: 豆瓣美女
link: https://github.com/luzefeng/DouBanMeinv
description: 以后周报该分级了 /w\
`````
