### ISSUE TITLE
Weekly/69 for 2017/3/22

### ISSUE THREAD

**Issue by ComMouse** [dyweb/weekly#17]
2017/3/22, 总第六十九期 -> @dyweb/mos

投稿:

Web
- [x] @at15
- [ ] @swaylq
- [ ] @ComMouse
- [ ] @JasonQSY
- [ ] @LukeXuan
- [ ] @mingzz
- [ ] @kdplus
- [ ] @Bluemit 
- [ ] @bjmiao
- [ ] @dbshch
- [x] @GigaFlower
- [ ] @jasonliu747
- [ ] @lmh16
- [ ] @ningxiaohan
- [ ] @PengZhenghao
- [ ] @XinJack
- [ ] @tq5124 

MOS
- [ ] @gaocegege
- [ ] @mrmiywj 
- [ ] @arrowrowe
- [ ] @codeworm96 
- [ ] @JasonQSY 

Other
- [ ] @dyweb/android-dev 
- [ ] @dyweb/ios-dev 

__投稿后请在上述名单中 *打钩* ，如果没有列出各位的账号，也欢迎补充上来~__

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by at15** [comment]
````yaml
name: System Deisgn Interview
link: https://github.com/donnemartin/system-design-primer
````

Though, to be honest, this kind of learning may only apply to interview

**Comment by at15** [comment]
````yaml
name: PHP the right way
link: https://github.com/codeguy/php-the-right-way
````
cc @ComMouse @JasonQSY

**Comment by at15** [comment]
````yaml
name: Though bot playbook
link: https://thoughtbot.com/playbook
````
cc @swaylq

**Comment by at15** [comment]
````yaml
name: IBM TJBot
link: https://github.com/ibmtjbot/tjbot
````

![image](https://cloud.githubusercontent.com/assets/5621298/23923879/a800fa0a-08c5-11e7-86d8-c1b29c586697.png)

**Comment by at15** [comment]
````yaml
name: DL0-?
link: https://github.com/hunkim/DeepLearningZeroToAll
````

**Comment by GigaFlower** [comment]
````yaml
name: History of front end
link: http://www.jianshu.com/p/8dc5c6aa01fc
````

**Comment by at15** [comment]
````yaml
name: Tinaydb
link: https://github.com/msiemens/tinydb
description: The current source code has 1200 lines of code (with about 40% documentation) and 1000 lines tests
````

The problem is 1200 - 1000 - 1200 * 0.4 < 0
