### ISSUE TITLE
Weekly/70 for 2017/4/19

### ISSUE THREAD

**Issue by ComMouse** [dyweb/weekly#18]
2017/4/19, 总第七十期 -> @dyweb/mos

投稿:

Web
- [ ] @at15
- [ ] @swaylq
- [ ] @ComMouse
- [ ] @JasonQSY
- [ ] @LukeXuan
- [ ] @mingzz
- [ ] @kdplus
- [ ] @Bluemit 
- [ ] @bjmiao
- [ ] @dbshch
- [ ] @GigaFlower
- [ ] @jasonliu747
- [ ] @lmh16
- [ ] @ningxiaohan
- [ ] @PengZhenghao
- [ ] @XinJack
- [ ] @tq5124 
- [ ] @hebingchang 

MOS
- [ ] @gaocegege
- [ ] @mrmiywj 
- [ ] @arrowrowe
- [ ] @codeworm96 
- [ ] @JasonQSY 

Other
- [ ] @dyweb/android-dev 
- [ ] @dyweb/ios-dev 

__投稿后请在上述名单中 *打钩* ，如果没有列出各位的账号，也欢迎补充上来~__

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by ComMouse** [comment]
```yaml
name: Source Han Serif
link: http://adobe.ly/SourceHanSerif
description: Adobe's serif open sourced fonts. Recommended from @gaocegege
cc: @gaocegege
```
@gaocegege

**Comment by at15** [comment]
````yaml
name:
link: https://github.com/jepsen-io/maelstrom
description: This allows students to write a Raft implementation in whatever language they are most comfortable with, without having to worry about discovery, network communication, daemonization, writing their own distributed test harness, and so on
cc: @gaocegege
````

@gaocegege

**Comment by at15** [comment]
````yaml
name: TerarkDB
link: https://terark.com/en/index
description: World's Fastest Storage Engine with Best Compression
cc: @mrmiywj @codeworm96
````

@mrmiywj @codeworm96

**Comment by at15** [comment]
````yaml
name: open-lambda
link: https://github.com/open-lambda/open-lambda
description: open source serverless implementation
````

cc @gaocegege @ComMouse

**Comment by at15** [comment]
````yaml
name: IBM OpenWhisk
link: https://github.com/openwhisk/openwhisk
description: Another open source serverless implementation well, IBM everywhere
`````

cc @gaocegege

**Comment by at15** [comment]
````
name:  Afterburner
link: https://github.com/afterburnerdb/afterburner
description: Interactive SQL analytics in your browser!
`````

**Comment by at15** [comment]
https://github.com/atech/postal

**Comment by at15** [comment]
http://appium.io/

**Comment by at15** [comment]
https://www.cs.princeton.edu/courses/archive/fall16/cos418/assignments.html yet another 6.824 @gaocegege

**Comment by at15** [comment]
https://github.com/mirage/irmin

**Comment by at15** [comment]
http://www.ece.ucsb.edu/~yuanxie/Advice.html cc @JasonQSY @mrmiywj @ComMouse

**Comment by at15** [comment]
WiscKey: Separating Keys from Values in SSD-Conscious Storage http://pages.cs.wisc.edu/~ll/papers/wisckey-slides.pdf cc @swaylq @mrmiywj @gaocegege

**Comment by at15** [comment]
https://testmysite.withgoogle.com/intl/en-gb/ cc @ComMouse

**Comment by ComMouse** [comment]
```yaml
name: WannaCrypt ransomware worm targets out-of-date systems
link: https://blogs.technet.microsoft.com/mmpc/2017/05/12/wannacrypt-ransomware-worm-targets-out-of-date-systems/
description: Simple analysis of the behavior of the worm by Microsoft.
```
WannaCrypt ransomware worm targets out-of-date systems
https://blogs.technet.microsoft.com/mmpc/2017/05/12/wannacrypt-ransomware-worm-targets-out-of-date-systems/
