### ISSUE TITLE
Weekly/71 for 2017/7/5

### ISSUE THREAD

**Issue by at15** [dyweb/weekly#20]
2017/7/5, 总第七十一期 -> @dyweb/mos

投稿:

Web
- [x] @at15
- [ ] @swaylq
- [ ] @ComMouse
- [ ] @JasonQSY
- [ ] @LukeXuan
- [ ] @mingzz
- [ ] @kdplus
- [ ] @Bluemit 
- [ ] @bjmiao
- [ ] @dbshch
- [ ] @GigaFlower
- [ ] @jasonliu747
- [ ] @lmh16
- [ ] @ningxiaohan
- [ ] @PengZhenghao
- [ ] @XinJack
- [ ] @tq5124 
- [ ] @hebingchang 

MOS
- [ ] @gaocegege
- [ ] @mrmiywj 
- [ ] @arrowrowe
- [ ] @codeworm96 
- [ ] @JasonQSY 

Other
- [ ] @dyweb/android-dev 
- [ ] @dyweb/ios-dev 

__投稿后请在上述名单中 *打钩* ，如果没有列出各位的账号，也欢迎补充上来~__

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by at15** [comment]
以后开 issue 也放到 bot 里好了... 以及以前的 issue 该关了吧? @ComMouse @codeworm96

**Comment by at15** [comment]
https://www.packet.net/

> The Promise of the Cloud Delivered on Bare Metal

**Comment by at15** [comment]
https://github.com/gemini-testing/gemini

Utility for regression testing of web pages using screenshots

**Comment by at15** [comment]
https://github.com/theupdateframework/tuf

**Comment by codeworm96** [comment]
```yaml
name: Akyuu.js
link: https://github.com/akyuujs
description: Yet another web framework based on express.js named Akyuu.
quote:  只是觉得名字有趣，具体没看...我是 koa2 用户
cc: arrowrowe
```
cc @arrowrowe
