### ISSUE TITLE
Weekly/59 for 2016/11/16

### ISSUE THREAD

**Issue by arrowrowe** [dyweb/weekly#6]
2016/11/16, 第十四循环第二次, 总第五十九期 -> @dyweb/mos

投稿:

Web
- [ ] @at15
- [ ] @swaylq
- [ ] @ComMouse
- [ ] @LukeXuan
- [ ] @kdplus
- [ ] @Bluemit
- [ ] @JasonQSY

MOS
- [ ] @gaocegege
- [x] @mrmiywj 
- [x] @arrowrowe
- [ ] @codeworm96 

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by arrowrowe** [comment]
```yaml
name: Angular Style Guide
link: https://github.com/johnpapa/angular-styleguide
description: a starting point for Angular development teams to provide consistency through good practices.
quote: 
cc: 
```

**Comment by mrmiywj** [comment]
```yaml
name: Ceylon language
link: https://ceylon-lang.org
description: A static type language... if you are interested in type system..
quote:
cc: 
```

**Comment by arrowrowe** [comment]
```yaml
name: Modern C++ Features
link: https://github.com/AnthonyCalandra/modern-cpp-features
description: a cheatsheet of modern C++ language and library features.
quote: 
cc: mrmiywj
```
