### ISSUE TITLE
Weekly/60 for 2016/11/23

### ISSUE THREAD

**Issue by arrowrowe** [dyweb/weekly#7]
2016/11/23, 第十四循环第三次, 总第六十期 -> @dyweb/mos

投稿:

Web
- [x] @at15
- [ ] @swaylq
- [ ] @ComMouse
- [ ] @LukeXuan
- [ ] @kdplus
- [ ] @Bluemit

MOS
- [ ] @gaocegege
- [ ] @mrmiywj 
- [x] @arrowrowe
- [ ] @codeworm96 
- [ ] @JasonQSY 

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by at15** [comment]
.... the sleepless mie

**Comment by at15** [comment]
````yaml
name: An Incredible Mechanical Ergonomic Keyboard
link: https://ergodox-ez.com/
description: Just $240
cc: kdplus gaocegege arrowrowe
````

**Comment by at15** [comment]
````yaml
name: Clarity
link: https://vmware.github.io/clarity/
description: UX guidelines, HTML/CSS framework, and Angular 2 components working together to craft exceptional experiences
cc: cjc
````

**Comment by at15** [comment]
````yaml
name: gitgo
link: https://github.com/ChimeraCoder/gitgo
description: go git library without using libgit and git binary
cc: gaocegege at15
````

**Comment by arrowrowe** [comment]
@at15 [第 26 期](https://github.com/dyweb/weekly/blob/master/2016/2016-03-30-weekly.md) 里有一堆 Java Git 的, 你当时 https://github.com/dyweb/web-stuff/issues/55#issuecomment-202679856 说一专毕设里要用到的...

**Comment by at15** [comment]
@arrowrowe 嗯, 当时准备写一个基于git的wik and/or pdf comment ... gitgo 是为了Ayi .../w\

**Comment by arrowrowe** [comment]
```yaml
name: PullApprove
link: https://about.pullapprove.com/
description: 
quote: 
cc: 
```
[![approve-by-comment.gif](https://about.pullapprove.com/static/img/approve-by-comment.gif)](https://about.pullapprove.com/)

**Comment by at15** [comment]
````yaml
name: playcanvas
link: https://github.com/playcanvas/engine
description: a web game engine with editor
cc: ComMouse
````

**Comment by at15** [comment]
````yaml
name: minio
link: https://github.com/minio/minio
description: a amazon s3 compatible object storage server
cc: gaocegege
````

**Comment by gaocegege** [comment]
```yaml
name: Cyclone
link: https://github.com/caicloud/cyclone
description: Cyclone is a cloud native CI/CD platform built for container workflow.
```

**Comment by at15** [comment]
````yaml
name: Clef
link: https://getclef.com/developer/
description: account solution
cc: ComMouse
````
