### ISSUE TITLE
Weekly/61 for 2016/11/30

### ISSUE THREAD

**Issue by arrowrowe** [dyweb/weekly#8]
2016/11/30, 总第六十一期 -> @dyweb/mos

投稿:

Web
- [x] @at15
- [ ] @swaylq
- [ ] @ComMouse
- [ ] @LukeXuan
- [ ] @kdplus
- [ ] @Bluemit

MOS
- [ ] @gaocegege
- [ ] @mrmiywj 
- [x] @arrowrowe
- [ ] @codeworm96 
- [ ] @JasonQSY 

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by at15** [comment]
咩.....

**Comment by arrowrowe** [comment]
```yaml
name: CSSReference
link: http://cssreference.io/
description: a free visual guide to CSS.
quote: 
cc: ComMouse, JasonQSY
```

**Comment by arrowrowe** [comment]
```yaml
name: Shinatra
link: https://github.com/benrady/shinatra
description: a simple web server in 5 lines of bash.
quote: 
cc: 
```
