### ISSUE TITLE
Weekly/62 for 2016/12/21

### ISSUE THREAD

**Issue by ComMouse** [dyweb/weekly#9]
2016/12/21, 总第六十二期 -> @dyweb/mos

投稿:

Web
- [x] @at15
- [ ] @swaylq
- [ ] @ComMouse
- [ ] @LukeXuan
- [ ] @kdplus
- [ ] @Bluemit
- [x] @JasonQSY 
- [x] @bjmiao

MOS
- [ ] @gaocegege
- [ ] @mrmiywj 
- [ ] @arrowrowe
- [ ] @codeworm96 
- [x] @JasonQSY 

投稿模板: (评论放在 yaml 块之后)

    ```yaml
    name: 
    link: 
    description: 
    quote: 
    cc: 
    ```

详细规范请参考 https://github.com/dyweb/mos/issues/1#issuecomment-257930244

关于 YAML,
- YAML: [The Official YAML Web Site](http://yaml.org/)
- Try it with the [Online YAML Parser](http://yaml-online-parser.appspot.com/)
- [Learn yaml in Y Minutes](https://learnxinyminutes.com/docs/yaml/)
- Python parser: [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)

**Comment by at15** [comment]
https://github.com/Tencent/bk-cmdb 抓到野生的CI一只 @ComMouse

**Comment by at15** [comment]
https://www.ipify.org/ a public ip address service

**Comment by at15** [comment]
https://github.com/gchq/CyberChef cc @arrowrowe pls proxy to imspace .... (forgot his gh id, maybe not in the org?)

**Comment by arrowrowe** [comment]
@at15 this is @spacemeowx2

**Comment by at15** [comment]
https://realm.io/ a mobile database for real time collaboration

**Comment by bjmiao** [comment]
https://github.com/joshuaduffy/dota2api 听说你们很多人都打Dota……
大概可以自己搞Dota助手之类的了……

**Comment by at15** [comment]
@bjmiao 哪有，我们都是爱学习的好孩子，从不玩游戏 .w.   (欢迎加入 http://steamcommunity.com/groups/dygalgame

**Comment by bjmiao** [comment]
果面……不打Dota，也不怎么推galgame。
What's more，没装Steam。
然而近来发现了一款很感兴趣的Galgame。Grand Old Academy: A Satirical Dating Sim

**Comment by JasonQSY** [comment]
```yaml
name: sudo-touchid
link: https://github.com/mattrajca/sudo-touchid
description: Use touchid on 2016 mbp for sudo authorization!
quote: 
cc: LukeXuan
```
